#config file for Extras, author is pixar02
#don't edit this !:
VR:


#Now you can edit what you want !
#spawn loaction
spawn:

#if players should teleport to the spawn if they join
teleport: true

#all configuration about void fall
Teleport:
    tele: true
    Y: 10