name: Extras
main: me.pixar02.Extras.Main
author: pixar02
version: 1.3.5

commands:
  espawn:
    description: teleports to spawn set in config.
    permission: ex.spawn
    permission-message: You do not have /<permission>
  esetspawn:
    description: sets sawn in the config.
    permission: ex.spawn
    permission-message: You do not have /<permission>
  ereload:
    description: reload plugins config.
    permission: ex.reload
    permission-message: You do not have /<permission>
    
permissions:
  ex.*:
    description: gives you all permissions
    children:
      ex.spawn: true
      ex.setspawn: true
      ex.reload: true
  ex.exempt:
    description: Allows you to NOT teleport to spawn
  ex.spawn:
    description: Allows you to teleport to spawn
  ex.reload:
    description: allows you to reload the config
  ex.setspawn:
    description: allows you to set the spawn location